name: Flutter Build

on:
  push:
    branches:
      - main   # workflow jalan setiap kali push ke branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'   # sesuaikan dengan versi Flutter kamu

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
  uses: actions/upload-artifact@v4
  with:
    name: app-release
    path: build/app/outputs/flutter-apk/app-release.apk
